version: "3.8"
services:
  db:
    image: postgres:latest
    hostname: "db"
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "more_tech"
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    entrypoint: /usr/bin/entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db


volumes:
  postgres_data:
