version: "3.8"
services:
  db:
    image: postgres:latest
    hostname: "db"
    container_name: db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "more_tech"
    ports:
      - "15432:5432"

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
