"""null keys

Revision ID: 331372466eb8
Revises: 1955a2c4043e
Create Date: 2022-10-08 16:04:10.393736

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '331372466eb8'
down_revision = '1955a2c4043e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'private_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'private_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
