"""change_type

Revision ID: 401a9a53b7b6
Revises: 9d48dd4dd068
Create Date: 2022-10-09 00:32:47.640348

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "401a9a53b7b6"
down_revision = "9d48dd4dd068"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("event", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("event", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("event", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("event", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###
